# plugin.yml
name: CipaUtils
version: 1.4
main: bzh.breizhhardware.cipautils.Main
api-version: 1.21
commands:
  nomorespawnprotect:
    description: Enable/disable spawn protection
    usage: /nomorespawnprotect - Toggle spawn protection
    aliases:
      - nsp
  waystone:
    description: Waystone command
    usage: /waystone
    aliases:
      - ws
  toggledeathmsg:
    description: Enable/disable death messages about grave recover
    usage: /toggledeathmsg
    aliases:
      - tdm
  cipautils:
    description: Commands for CipaUtils
    usage: /cipautils
    aliases:
      - cu
  chunkloader:
    description: Give a chunkloader
    usage: /chunkloader give
    aliases:
      - cl
permissions:
  nomorespawnprotect.admin:
    description: Allow to manage spawn protection
    default: op
  cipautils.waystone.use:
    description: Allow to use waystones
    default: true
  cipautils.waystone.give:
    description: Allow to give waystones
    default: op
  cipautils.waystone.admin:
    description: Allow to manage waystones
    default: op
