# plugin.yml
name: CipaUtils
version: 1.4
main: bzh.breizhhardware.cipautils.Main
api-version: 1.21
commands:
  nomorespawnprotect:
    description: Active ou désactive la protection du spawn
    usage: /nomorespawnprotect - Bascule la protection du spawn (active/désactive)
  waystone:
    description: Commandes pour les waystones
    usage: /waystone
  toggledeathmsg:
    description: Active/désactive le message d'info sur la récupération automatique des tombes
    usage: /toggledeathmsg
  cipautils:
    description: Commands for CipaUtils
    usage: /cipautils
    aliases:
      - cu
permissions:
  nomorespawnprotect.admin:
    description: Permet de contrôler les paramètres du plugin
    default: op
  cipautils.waystone.use:
    description: Permet d'utiliser les waystones
    default: true
  cipautils.waystone.give:
    description: Permet d'obtenir des items waystone
    default: op
  cipautils.waystone.admin:
    description: Permet de détruire toutes les waystones
    default: op
